#!/usr/bin/env python3
"""What blocks each C# interface from becoming a complete Rust trait.

An interface must become a trait before an interface-typed field can be
translated at all (D1 settles the field; the trait was the open half). The
question "why can this one not be generated" was previously answered by reading
the converter's source, which is how it stayed an opinion.

This makes it a MEASUREMENT, and derives it from the converter itself: the
per-member analysis here is `Emitter.interface_report()`, the same call
`scripts/emit.py --interfaces` emits from. The published table therefore cannot
disagree with what the converter does -- a second, hand-kept list of blockers
would drift the first time a mapping landed.

Reason names are documented in `interface_traits.blocker_reasons` in
rulesdb/rules/csharp_core.json. They are kept apart because each is a different
piece of work:

  * `type_not_in_corpus` counts the INGEST boundary -- no converter change
    reaches it.
  * `type_without_definition` counts types we hold but do not yet emit.
  * `generic_method`, `overload`, `name_collision` are Rust language limits
    that need a naming or dispatch rule.
  * `bcl_unmapped` is a missing mapping rule, the cheapest of the five.

Writes:  docs/status/interfaces.json   machine-readable, one entry per member
         docs/status/interfaces.md     the same thing as a table
Run:     python3 scripts/interface_census.py
Log:     ./tmp/logs/interface_census.log
Exit:    0 always -- this is a measurement, not a gate.
"""

from __future__ import annotations

import argparse
import collections
import json
import logging
import sqlite3
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "core"))


def repo_root() -> Path:
    return Path(subprocess.run(["git", "rev-parse", "--show-toplevel"],
                               capture_output=True, text=True,
                               check=True).stdout.strip())


def blocked_types(report: list[dict]) -> list[dict]:
    """Every C# type that blocked a member, with how often and why."""
    seen: dict[tuple[str, str], dict] = {}
    for r in report:
        for entry in r["members"]:
            for b in entry["blockers"]:
                key = (b["type"], b["reason"])
                row = seen.setdefault(key, {"type": b["type"],
                                            "reason": b["reason"],
                                            "members": 0, "interfaces": set()})
                row["members"] += 1
                row["interfaces"].add(r["key"])
    out = [{**row, "interfaces": sorted(row["interfaces"])}
           for row in seen.values()]
    out.sort(key=lambda r: (-r["members"], r["reason"], r["type"]))
    return out


def as_markdown(doc: dict) -> str:
    """The census as a table. Generated -- the .json is the same data."""
    L: list[str] = []
    a = L.append
    a("# Interfaces: what blocks each one from becoming a Rust trait")
    a("")
    a("GENERATED by `scripts/interface_census.py` from the corpus database and")
    a("the converter's own analysis (`Emitter.interface_report`). Do not edit:")
    a("a hand-kept copy drifts the first time a type mapping lands.")
    a("")
    a(f"Corpus run {doc['corpus']['run']}, config `{doc['corpus']['config']}`, "
      f"source commit `{doc['corpus']['commit'][:12]}`.")
    a("")
    s = doc["summary"]
    a(f"**{s['complete']} of {s['interfaces']} interfaces generate complete**; "
      f"{s['withheld']} are withheld. Of {s['members_total']} members, "
      f"{s['members_emitted']} can be expressed and {s['members_blocked']} "
      f"cannot.")
    a("")
    a("A trait is emitted only when EVERY member and EVERY inherited interface")
    a("can be expressed. A trait missing members would carry a name it does not")
    a("live up to, and its shape would change as mappings land.")
    a("")
    a("## Per interface")
    a("")
    a("| C# interface | members | emitted | blocked | bases | complete |")
    a("|---|---:|---:|---:|---:|---|")
    for r in doc["interfaces"]:
        a(f"| `{r['key']}` | {len(r['members'])} | {r['members_emitted']} | "
          f"{r['members_blocked']} | {len(r['bases'])} | "
          f"{'yes' if r['complete'] else 'no'} |")
    a("")
    a("`members` counts emittable members, not corpus rows: a C# property is")
    a("recorded three times over (the property and its two accessors) and")
    a("becomes a getter and a setter.")
    a("")
    a("## What blocks them, by type")
    a("")
    a("| C# type | reason | members | interfaces |")
    a("|---|---|---:|---|")
    for b in doc["blocked_types"]:
        a(f"| `{b['type']}` | {b['reason']} | {b['members']} | "
          f"{len(b['interfaces'])} |")
    a("")
    a("## What blocks them, by reason")
    a("")
    a("| reason | members |")
    a("|---|---:|")
    for reason, n in doc["summary"]["by_reason"]:
        a(f"| {reason} | {n} |")
    a("")
    a("Reason names are defined in `interface_traits.blocker_reasons` in")
    a("`rulesdb/rules/csharp_core.json`.")
    a("")
    a("## Every blocked member")
    a("")
    for r in doc["interfaces"]:
        blocked = [e for e in r["members"] if not e["rust"]]
        bad_bases = [b for b in r["bases"] if not b["rust"]]
        if not blocked and not bad_bases and not r["blockers"]:
            continue
        a(f"### `{r['key']}`")
        a("")
        for b in r["blockers"]:
            a(f"- **the declaration itself**: {b['reason']}")
        for b in bad_bases:
            why = ", ".join(x["reason"] for x in b["blockers"]) or "unknown"
            a(f"- **inherits** `{b['csharp']}`: {why}")
        for e in blocked:
            why = "; ".join(f"`{x['type']}` {x['reason']}"
                            for x in e["blockers"]) or "unknown"
            a(f"- `{e['csharp']}`: {why}")
        a("")
    return "\n".join(L).rstrip() + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--db", default="rulesdb/patterns.db")
    args = ap.parse_args()

    root = repo_root()
    (root / "tmp" / "logs").mkdir(parents=True, exist_ok=True)
    log = logging.getLogger("interface_census")
    log.setLevel(logging.INFO)
    for h in (logging.FileHandler(root / "tmp" / "logs" / "interface_census.log",
                                  mode="w"), logging.StreamHandler(sys.stdout)):
        h.setFormatter(logging.Formatter("%(message)s"))
        log.addHandler(h)

    from emit import Emitter
    con = sqlite3.connect(f"file:{root / args.db}?mode=ro", uri=True)
    em = Emitter(con, log)
    report = em.interface_report()
    run = con.execute("SELECT id, renode_commit, config FROM corpus_run "
                      "ORDER BY id DESC LIMIT 1").fetchone()

    by_reason: collections.Counter = collections.Counter()
    for r in report:
        for e in r["members"]:
            for b in e["blockers"]:
                by_reason[b["reason"]] += 1

    doc = {
        "note": "GENERATED by scripts/interface_census.py. Do not edit -- the "
                "analysis comes from the converter, so a hand edit here would "
                "state something the converter does not do.",
        "corpus": {"run": run[0], "commit": run[1], "config": run[2]},
        "summary": {
            "interfaces": len(report),
            "complete": sum(1 for r in report if r["complete"]),
            "withheld": sum(1 for r in report if not r["complete"]),
            "members_total": sum(len(r["members"]) for r in report),
            "members_emitted": sum(r["members_emitted"] for r in report),
            "members_blocked": sum(r["members_blocked"] for r in report),
            "by_reason": sorted(by_reason.items(), key=lambda kv: (-kv[1], kv[0])),
        },
        "blocked_types": blocked_types(report),
        "interfaces": report,
    }
    con.close()

    out = root / "docs" / "status"
    out.mkdir(parents=True, exist_ok=True)
    (out / "interfaces.json").write_text(
        json.dumps(doc, indent=1, sort_keys=False) + "\n")
    (out / "interfaces.md").write_text(as_markdown(doc))

    s = doc["summary"]
    log.info("%d interface(s): %d complete, %d withheld",
             s["interfaces"], s["complete"], s["withheld"])
    log.info("%d member(s): %d expressible, %d blocked",
             s["members_total"], s["members_emitted"], s["members_blocked"])
    log.info("")
    log.info("%-28s %s", "reason", "members")
    for reason, n in s["by_reason"]:
        log.info("%-28s %7d", reason, n)
    log.info("")
    log.info("worst blocking types:")
    for b in doc["blocked_types"][:10]:
        log.info("    %-58s %-24s %3d", b["type"], b["reason"], b["members"])
    log.info("")
    log.info("wrote docs/status/interfaces.json and docs/status/interfaces.md")
    return 0


if __name__ == "__main__":
    sys.exit(main())
