graph LR
    ADCChannel --> IPeripheral
    ADCChannelSource --> VoltageSample
    AESServiceProvider --> IBusController
    AESServiceProvider --> InternalMemoryManager
    AFESampleFIFO --> MAX86171
    AINTC --> DoubleWordRegister
    AMDCFIFlash --> MappedMemory
    AMDCFIFlash --> SectorRegion
    APICMessageHelper --> IAPICPeripheral
    ARM_GenericInterruptController --> CPUEntry
    ARM_GenericInterruptController --> IBusController
    ARM_GenericInterruptController --> InterruptsDecoder
    ARM_GenericInterruptController --> QuadWordRegisterCollection
    ARM_GenericTimer --> IClockSource
    ARM_GenericTimer --> QuadWordRegisterCollection
    ARM_GenericTimer --> TimerUnit
    ARM_GlobalTimer --> ICPU
    ARM_GlobalTimer --> LimitTimer
    ARM_PrivateTimer --> LimitTimer
    ARM_SMMUv3 --> Domain
    ARM_SMMUv3 --> IBusController
    ARM_SMMUv3 --> IMachine
    ARM_SMMUv3 --> IPeripheral
    ARM_SMMUv3BusController --> ARM_SMMUv3
    ARM_SMMUv3ExternalMmu --> ARM_SMMUv3
    ARM_SMMUv3ExternalMmu --> ICPUWithExternalMmu
    ARM_SP804_Timer --> LimitTimer
    ARMv7A --> ARM_GenericTimer
    ARMv8A --> ARM_GenericInterruptController
    ARMv8A --> ARM_GenericTimer
    ARMv8R --> ARM_GenericInterruptController
    ARMv8R --> ARM_GenericTimer
    AS6221 --> IMachine
    AS6221 --> LimitTimer
    AT91_InterruptibleTimer --> LimitTimer
    ATAPI --> ByteRegisterCollection
    ATAPI --> IAtapiPeripheral
    ATAPI --> WordRegisterCollection
    AbsolutePointerHandler --> FrameBufferDisplayWidget
    ActualLogger --> LogEntry
    ActualLogger --> LogSourcesMap
    AddressTranslationTable --> MPFS_PCIe
    AesEcbState --> AesProvider
    AlarmConfig --> STM32F4_RTC
    AlarmConfig --> TimerConfig
    AlgorithmState --> STM32H7_CRYPTO
    Allegro_E310 --> Mailbox
    AmbiqApollo4_ADC --> Slot
    AmbiqApollo4_GPIO --> GPIO
    AmbiqApollo4_IOMaster --> Fifo
    AmbiqApollo4_IOMaster --> IMachine
    AmbiqApollo4_RTC --> BCDValueField
    AmbiqApollo4_RTC --> RTCTimer
    AmbiqApollo4_Security --> IBusController
    AmbiqApollo4_SystemTimer --> CaptureRegister
    AmbiqApollo4_SystemTimer --> CompareRegister
    AmbiqApollo4_SystemTimer --> GPIO
    AmbiqApollo4_SystemTimer --> LimitTimer
    AmbiqApollo4_Timer --> InternalTimer
    AmbiqApollo4_Watchdog --> LimitTimer
    AndNode --> AstNode
    AndesATCGPIO100 --> GPIOInterruptManager
    AndesATCRTC100 --> LimitTimer
    AndesATCSPI200 --> IBusController
    AndesATCSPI200 --> IMachine
    AndesATCWDT200_Watchdog --> IMachine
    AndesATCWDT200_Watchdog --> LimitTimer
    Andes_AndeStarV5Extension --> IBusController
    Andes_AndeStarV5Extension --> RiscV32
    ArbitraryTimestampSamplesDataBlock --> SafeBinaryReader
    ArbitraryTimestampSamplesDataBlock --> TimestampedRESDSample
    ArchitectureDecoder --> BaseRiscV
    ArchitectureDecoder --> IMachine
    ArduCAMMini2MPPlus --> HostCamera
    ArduCAMMini2MPPlus --> OV2640
    Arm --> ArmPerformanceMonitoringUnit
    Arm --> ArmSignalsUnit
    Arm --> SemihostingHandler
    ArmPerformanceMonitoringUnit --> Arm
    ArmSignalsUnit --> ArmSnoopControlUnit
    ArmSignalsUnit --> IMachine
    ArmSignalsUnit --> IRegistrationPoint
    ArmSnoopControlUnit --> ArmSignalsUnit
    ArmSysCtl --> IMachine
    AtCommandModem --> IMachine
    AthenaX5200 --> AESServiceProvider
    AthenaX5200 --> DSAServiceProvider
    AthenaX5200 --> InternalMemoryManager
    AthenaX5200 --> MessageAuthenticationServiceProvider
    AthenaX5200 --> PseudorandomBitGenerator
    AthenaX5200 --> RSAServiceProvider
    Atmel91SystemTimer --> AT91_InterruptibleTimer
    Atmel91SystemTimer --> LimitTimer
    AtomicState --> IEmulationElement
    AutoRepaintingVideo --> IMachine
    AutoRepaintingVideo --> IManagedThread
    BCDValueField --> IPeripheral
    BUFC_Buffer --> EFR32xG24_Radio
    BUFC_Buffer --> Machine
    BackendSourceIdPair --> ILoggerBackend
    BackendState --> LogLevel
    BackendTerminal --> IMachine
    BackendTerminal --> IUART
    BackingFile --> FilePath
    Bank --> LockRegister
    Bank --> MappedMemory
    Bank --> STM32H7_FlashController
    BaseARMv8 --> PseudorandomNumberGenerator
    BaseCPU --> IMachine
    BaseCPU --> SealableValue
    BaseCPU --> Sleeper
    BaseCPU --> Synchronizer
    BaseCPU --> TimeHandle
    BaseGPIOPort --> IMachine
    BaseProfiler --> TranslationCPU
    BaseRegisterCollection --> IPeripheral
    BaseRegisterCollection --> RegisterSelector
    BaseRiscV --> ArchitectureDecoder
    BaseRiscV --> CoreLocalInterruptController
    BaseRiscV --> ExternalPMPBase
    BaseRiscV --> IRiscVTimeProvider
    BasicBytePeripheral --> IBusController
    BasicBytePeripheral --> IMachine
    BasicDoubleWordPeripheral --> IBusController
    BasicDoubleWordPeripheral --> IMachine
    BasicNetwork --> IBasicNetworkNode
    BasicWordPeripheral --> IBusController
    BasicWordPeripheral --> IMachine
    BetrustedEcI2C --> II2CPeripheral
    BetrustedSocI2C --> II2CPeripheral
    BitAccess --> IBusController
    BitBanding --> IBusController
    BitBangHelper --> Decoder
    BitBangHelper --> Encoder
    BitBangHelper --> IEmulationElement
    BitConcatenator --> BitStream
    BitPatternDetector --> IPeripheral
    Block --> PeripheralAccessMethods
    BlockPythonEngine --> ICPUWithHooks
    BlockPythonEngine --> IMachine
    BusPeripheralsHooksPythonEngine --> IBusController
    BusPeripheralsHooksPythonEngine --> IBusPeripheral
    ByteArrayWithAccessTracking --> IPeripheral
    CAES_ADC --> LimitTimer
    CANTester --> CANMatcher
    CANTester --> CANMessageFrame
    CC1200 --> ByteRegisterCollection
    CC1200 --> CircularBuffer
    CC2520 --> Address
    CC2520 --> ByteRegisterCollection
    CC2538FlashController --> MappedMemory
    CC2538RF --> Address
    CC2538RF --> DoubleWordRegister
    CC2538RF --> PseudorandomNumberGenerator
    CC2538_Cryptoprocessor --> AesProvider
    CC2538_Cryptoprocessor --> IBusController
    CC2538_GPIO --> GPIOInterruptManager
    CC2538_SSI --> CircularBuffer
    CCChannel --> IPeripheral
    CCChannel --> LimitTimer
    CDROM --> Stream
    CFIFlash --> SerializableStreamView
    CPUControl --> BaseCPU
    CPUEntry --> ARM_GenericInterruptController
    CPUEntry --> Affinity
    CPUEntry --> IARMSingleSecurityStateCPU
    CPUEntry --> QuadWordRegisterCollection
    CPUEntryWithTwoSecurityStates --> IARMTwoSecurityStatesCPU
    CPUTracer --> Arm
    CPUTracer --> IBusController
    CadenceGEM --> IBusController
    CadenceGEM --> LimitTimer
    Cadence_I2C --> CadenceInterruptFlag
    Cadence_I2C --> II2CPeripheral
    Cadence_SPI --> CadenceInterruptFlag
    Cadence_SPI --> ISPIPeripheral
    Cadence_TTC --> TimerUnit
    Cadence_UART --> CadenceInterruptFlag
    Cadence_UART --> IMachine
    Cadence_USB --> ByteRegisterCollection
    Cadence_USB --> DMACore
    Cadence_USB --> IMachine
    Cadence_USB --> WordRegisterCollection
    Cadence_WDT --> LimitTimer
    Cadence_xSPI --> CadenceInterruptFlag
    CalculateCRCCommand --> CRCEngine
    Caliptra_I3C --> DatType
    Caliptra_I3C --> DctType
    Capability --> IPCIePeripheral
    CaptureCompareChannel --> GPIO
    CaptureCompareChannel --> LimitTimer
    CaptureCompareChannel --> STM32_Timer
    CaptureRegister --> AmbiqApollo4_SystemTimer
    Channel --> Allegro_E310
    Channel --> DmaEngine
    Channel --> DoubleWordRegister
    Channel --> EFR32MG12_LDMA
    Channel --> EFR32MG24_LDMA
    Channel --> EFR32xG22_LDMA
    Channel --> EOSS3_ADC
    Channel --> IBusController
    Channel --> ICPU
    Channel --> IGPIO
    Channel --> IPeripheral
    Channel --> LimitTimer
    Channel --> MPFS_PDMA
    Channel --> NRF52840_GPIOTasksEvents
    Channel --> NXP_INTMUX
    Channel --> NXP_eDMA_Channels
    Channel --> PAC1934
    Channel --> PL330_DMA
    Channel --> RenesasDA_DMABase
    Channel --> RenesasRZG_DMAC
    Channel --> STM32G0DMA
    Channel --> STM32LDMA
    Channel --> STM32WBA55_GPDMA
    Channel --> TegraDma
    Channel --> UDMA
    Channel --> VybridDma
    Channel --> WordRegisterCollection
    Channel --> ZynqMP_IPI
    ClockChannel --> LimitTimer
    Cluster --> IMachine
    Command --> Cadence_xSPI
    Command --> CommandsManager
    Command --> ISPIPeripheral
    Command --> Monitor
    CommandsEngine --> IMXRT_FlexSPI
    CommandsManager --> ICpuSupportingGdb
    CommunicationHandler --> CommandsManager
    CommunicationHandler --> GdbStub
    CompareChannel --> IPeripheral
    CompareChannel --> LimitTimer
    CompareRegister --> AmbiqApollo4_SystemTimer
    CompareRegister --> ComparingTimer
    CompareRegister --> GPIO
    CompareRegister --> LimitTimer
    ComparingTimer --> IClockSource
    ComparingTimer --> IPeripheral
    Condition --> RenesasRA_IIC
    Condition --> RenesasRZG_IIC
    ConfigurationManager --> ConfigSource
    ConfigurationUSBDescriptor --> InterfaceUSBDescriptor
    Connection --> DA16200
    ConsoleIOSource --> UTF8Checker
    ConsolePort --> ConsolePort
    ConsolePort --> VirtIOMMIOConsole
    ConsolePort --> Virtqueue
    ConsoleWindowBackendAnalyzer --> IConsoleBackendAnalyzerProvider
    ConstantFrequencySamplesDataBlock --> SafeBinaryReader
    ConstantFrequencySamplesDataBlock --> SamplesData
    Context --> CommunicationHandler
    Context --> ObjectCreator
    CoreLevelInterruptor --> IMachine
    CoreLocalInterruptController --> BaseRiscV
    CoreLocalInterruptController --> IMachine
    CortexM --> CortexMImplementationDefinedAttributionUnit
    CortexM --> NVIC
    CortexMDisassemblerWrapper --> IFlaglessDisassembler
    CpuThreadPauseGuard --> TranslationCPU
    DA16200 --> Connection
    DA16200 --> DataModeState
    DA16200 --> NetworkAddress
    DMAChannel --> FrameAssembler
    DMAChannel --> LimitTimer
    DMAChannel --> SynopsysDWCEthernetQualityOfService
    DMAChannelContext --> DmaEngine
    DMAChannelContext --> NPCX_MDMA
    DMACore --> Cadence_USB
    DSAServiceProvider --> IBusController
    DSAServiceProvider --> InternalMemoryManager
    DWT --> LimitTimer
    DataBlockEnumerator --> LowLevelRESDParser
    DataBlockEnumerator --> SafeBinaryReader
    DataModeState --> DA16200
    Decoder --> IEmulationElement
    DelayedInvalidationContext --> IHasDelayedInvalidationContext
    DeprecatedSDCard --> SerializableStreamView
    Descriptor --> IBusController
    Descriptor --> IPeripheral
    Descriptor --> SynopsysEthernetMAC
    Destination --> IGPIOReceiver
    DeviceHandlingHelpers --> Monitor
    DeviceRegisters --> BitTimingRegister
    DeviceRegisters --> ErrorStatusRegister
    DeviceRegisters --> FifoAssignmentRegister
    DeviceRegisters --> FilterActiveRegister
    DeviceRegisters --> FilterMasterRegister
    DeviceRegisters --> FilterModeRegister
    DeviceRegisters --> FilterScaleRegister
    DeviceRegisters --> InterruptEnableRegister
    DeviceRegisters --> MailboxIdentifierRegister
    DeviceRegisters --> MasterControlRegister
    DeviceRegisters --> MasterStatusRegister
    DeviceRegisters --> ReceiveFifoRegister
    DeviceRegisters --> TransmitStatusRegister
    DevicesConfig --> IMachine
    DmaBufferDescriptorsQueue --> IBusController
    DmaBufferDescriptorsQueue --> IPeripheral
    DmaEngine --> IBusController
    Domain --> ARM_SMMUv3
    DomainHandler --> IMachine
    DummyLINPeripheral --> ILINEntry
    DummySENTTransmitter --> FastMessage
    DummySENTTransmitter --> SlowMessage
    DummyUSBDevice --> ConfigurationUSBDescriptor
    EFR32MG12_LDMA --> DmaEngine
    EFR32MG24_LDMA --> DmaEngine
    EFR32MG24_LDMA --> Machine
    EFR32_GPCRC --> CRCEngine
    EFR32_GenericI2CController --> II2CPeripheral
    EFR32_GenericUSART --> ISPIPeripheral
    EFR32_RTCC --> EFR32_RTCCCounter
    EFR32_RTCCCounter --> CCChannel
    EFR32_RTCCCounter --> IMachine
    EFR32_RTCCCounter --> LimitTimer
    EFR32_Timer --> LimitTimer
    EFR32xG22_LDMA --> DmaEngine
    EFR32xG22_LDMA --> Machine
    EFR32xG24_FlashUserData --> Machine
    EFR32xG24_Radio --> BUFC_Buffer
    EFR32xG24_Radio --> CortexM
    EFR32xG24_Radio --> FRC_FrameDescriptor
    EFR32xG24_Radio --> LimitTimer
    EFR32xG24_Radio --> Machine
    EFR32xG24_Radio --> MappedMemory
    EFR32xG24_Radio --> PROTIMER_CaptureCompareChannel
    EFR32xG24_Radio --> PROTIMER_TimeoutCounter
    EFR32xG24_SYSRTC --> ComparingTimer
    EFR32xG24_SYSRTC --> LimitTimer
    EFR32xG2_AES_1 --> Machine
    EFR32xG2_BURTC --> ComparingTimer
    EFR32xG2_CMU_3 --> EFR32xG2_DPLL_1
    EFR32xG2_CMU_3 --> ICMU_EFR32xG2
    EFR32xG2_CMU_3 --> IHFXO_EFR32xG2
    EFR32xG2_DCDC_2 --> ICMU_EFR32xG2
    EFR32xG2_DPLL_1 --> ICMU_EFR32xG2
    EFR32xG2_EMU_3 --> ICMU_EFR32xG2
    EFR32xG2_EUSART_2 --> ISPIPeripheral
    EFR32xG2_EUSART_2 --> Machine
    EFR32xG2_GPCRC --> CRCEngine
    EFR32xG2_HFRCO_2 --> ICMU_EFR32xG2
    EFR32xG2_HFXO_2 --> LimitTimer
    EFR32xG2_HFXO_2 --> Machine
    EFR32xG2_HFXO_3 --> ICMU_EFR32xG2
    EFR32xG2_HFXO_3 --> LimitTimer
    EFR32xG2_LFRCO_2 --> ICMU_EFR32xG2
    EFR32xG2_LFXO_1 --> ICMU_EFR32xG2
    EFR32xG2_MSC_3 --> CPUCore
    EFR32xG2_MSC_3 --> LimitTimer
    EFR32xG2_MSC_3 --> Machine
    EFR32xG2_PRS_3 --> EFR32xG2_HFXO_3
    EFR32xG2_PRS_3 --> EFR32xG2_SYSRTC_1
    EFR32xG2_PRS_3 --> ICMU_EFR32xG2
    EFR32xG2_RNGCTRL --> Machine
    EFR32xG2_RTCC --> EFR32_RTCCCounter
    EFR32xG2_SEMAILBOX_1 --> Machine
    EFR32xG2_SEMAILBOX_1 --> Silabs_SecureElement
    EFR32xG2_SMU_1 --> Machine
    EFR32xG2_SYSCFG_3 --> ICMU_EFR32xG2
    EFR32xG2_SYSRTC_1 --> LimitTimer
    EFR32xG2_SYSRTC_1 --> Machine
    EFR32xG2_TIMER_1 --> ICMU_EFR32xG2
    EFR32xG2_TIMER_1 --> LimitTimer
    EFR32xG2_USART_0 --> ISPIPeripheral
    EFR32xG2_USART_0 --> LimitTimer
    EFR32xG2_USART_0 --> Machine
    EFR32xg13FlashController --> MappedMemory
    EHCIHostController --> IBusController
    EHCIHostController --> IMachine
    EHCIHostController --> IManagedThread
    EHCIHostController --> IUSBPeripheral
    EHCIHostController --> PortStatusAndControlRegister
    EHCIHostController --> QueueHead
    EHCIHostController --> Ulpi
    ENC28J60 --> ByteRegisterCollection
    ENC28J60 --> WordRegisterCollection
    EOSS3_IntrCtrl --> GPIOInterruptManager
    EOSS3_PacketFIFO --> PacketFifoBase
    EOSS3_SPI_DMA --> DesignWare_SPI
    EOSS3_SPI_DMA --> IBusController
    EOSS3_SimplePeriodicTimer --> LimitTimer
    EOSS3_SystemDMABridge --> UDMA
    EOSS3_Voice --> IManagedThread
    EOSS3_Voice --> PCMDecoder
    EcamLookupResult --> IPCIePeripheral
    EgisET171_AOSMU --> IHasFrequency
    EmberRadio --> IBusController
    EmberRadio --> IMachine
    Emios --> DoubleWordRegister
    Emulation --> CachingFileFetcher
    EmulationManager --> Emulation
    EmulatorController --> IMachine
    Encoder --> IEmulationElement
    EventEntry --> INRFEventProvider
    ExactSampleThread --> IMachine
    ExecutionTracer --> TraceWriter
    ExecutionTracer --> TraceWriterBuilder
    ExternalMmuBase --> ICPUWithExternalMmu
    ExternalPMPBase --> BaseRiscV
    ExternalsHandler --> Emulation
    Fifo --> IPeripheral
    FocalTechFT9001_Reset --> IMachine
    FoundRegistrationInfo --> BusRangeRegistration
    FoundRegistrationInfo --> PeripheralAccessMethods
    FoundRegistrationInfo --> PeripheralCollection
    FrameAssembler --> IEmulationElement
    FrameBufferDisplayWidget --> IOHandler
    FrameBufferDisplayWidget --> IPixelConverter
    FrameBufferTester --> IPixelConverter
    FrameBufferTester --> IVideo
    FrameProfilerContext --> ProfilerStack
    FrameProfilerContext --> TranslationCPU
    FrameTrackingCollapsedStackProfiler --> FrameProfilerContext
    GPIOAlternateFunction --> STM32F1GPIOPort
    GPIOAlternateFunction --> STM32_GPIOPort
    GPIOConnection --> RenesasDA14_GPT
    GPIOController --> XilinxGPIOPS
    GPIOGate --> GPIO
    GPIOInterruptManager --> EventRisingCollection
    GPIOInterruptManager --> GPIO
    GPIOLine --> BaseGPIOPort
    GPIOPythonEngine --> IGPIOWithHooks
    GPIORedirector --> IEmulationElement
    GPIORedirector --> IGPIO
    GPTChannel --> LimitTimer
    GPTChannel --> RenesasRA_GPT
    GPTChannel --> RenesasRZG_GPT
    GaislerAHBPlugAndPlayInfo --> GaislerAHBPlugAndPlayRecord
    GaislerAHBPlugAndPlayInfo --> IMachine
    GaislerAHBPlugAndPlayRecord --> Bar
    GaislerAHBPlugAndPlayRecord --> IdReg
    GaislerAPBController --> GaislerAPBPlugAndPlayRecord
    GaislerAPBController --> IMachine
    GaislerAPBPlugAndPlayRecord --> Bar
    GaislerAPBPlugAndPlayRecord --> IdReg
    GaislerEth --> IBusController
    GaislerEth --> RegsValues
    GaislerMIC --> GPIO
    Gaisler_FaultTolerantMemoryController --> AMDCFIFlash
    Gaisler_FaultTolerantMemoryController --> MappedMemory
    Gaisler_GPIO --> IGPIO
    Gaisler_GPTimer --> TimerUnit
    GdbStub --> CommandsManager
    GdbStub --> CommunicationHandler
    GdbStub --> ICpuSupportingGdb
    GdbStub --> PacketBuilder
    GdbStub --> SocketServerProvider
    GenericSpiFlash --> ByteRegister
    GenericSpiFlash --> MappedMemory
    GenericSpiFlash --> WordRegister
    GigaDevice_GD25LQ --> ByteRegisterCollection
    GigaDevice_GD25LQ --> MappedMemory
    GroupCollection --> CPUEntry
    HPET --> QuadWordRegisterCollection
    HPSHostController --> STM32F7_I2C
    HS3001 --> IMachine
    Handler --> SetAndRevertAfterCommand
    HiFive_PWM --> ComparingTimer
    HiFive_PWM --> IMachine
    HiFive_PWM --> LimitTimer
    HookDescriptorBase --> ICpuSupportingGdb
    HookWrapper --> IBusPeripheral
    I2CHost --> II2CPeripheral
    I2CPeripheralBase --> SimpleCache
    ICM20948 --> ByteRegisterCollection
    ICM20948 --> IMachine
    ICM20948 --> IManagedThread
    ICP_101xx --> CRCEngine
    ICP_101xx --> IMachine
    IMXRT700_MICFIL --> DataChannel
    IMXRT700_MICFIL --> IManagedThread
    IMXRT700_MICFIL --> PCMDecoder
    IMXRT700_MessagingUnit --> InstanceData
    IMXRT700_SAI --> Transceiver
    IMXRT700_SYSCON0 --> IMXRT700_DmaMux
    IMXRT700_SYSCON1 --> IMXRT700_DmaMux
    IMXRT_FlexSPI --> CommandsEngine
    IMXRT_FlexSPI --> RandomAccessQueue
    IMXRT_LPSPI --> DataMatcher
    IMXRT_LPSPI --> ISPIPeripheral
    IMXRT_LPSPI --> TCFifoCmd
    IMXRT_PWM --> ComparingTimer
    IMX_GPTimer --> ComparingTimer
    IMX_TRNG --> PseudorandomNumberGenerator
    IOAPIC --> APICMessageHelper
    IOHandler --> FrameBufferDisplayWidget
    IOHandler --> IEventSource
    IOHandler --> IKeyboard
    IOHandler --> PointerHandler
    IPpacket --> PseudoHeader
    ISP1761 --> IMachine
    ISP1761 --> IUSBPeripheral
    ISP1761 --> PTD
    ISP1761 --> PortStatusAndControlRegister
    ISSI_IS25WP --> ByteRegister
    ISSI_IS25WP --> QuadWordRegister
    ISSI_IS25WP --> WordRegister
    InnerTimer --> LimitTimer
    Instruction --> PL330_DMA
    Instruction --> Table
    Instructions --> Table
    InterfaceDescriptor --> IMACInterface
    InterfaceDescriptor --> IMachine
    InterfaceUSBDescriptor --> EndpointUSBDescriptor
    InternalClock --> LimitTimer
    InternalReceiver --> STM32WBA_EXTI
    InternalReceiver --> STM32_SYSCFG
    InternalTimer --> ComparingTimer
    InternalTimer --> InternalTimerBlock
    InternalTimer --> VeeR_EL2
    Interrupt --> S32K3XX_MiscellaneousSystemControlModule
    InterruptConfig --> EOSS3_IntrCtrl
    InterruptHandler --> IGPIO
    InterruptManager --> IPeripheral
    InterruptPythonEngine --> ICPUWithHooks
    InterruptPythonEngine --> IMachine
    InterruptSource --> VeeR_EL2_PIC
    IoContext --> BitStream
    IrqContext --> IPlatformLevelInterruptController
    IrqNode --> IGPIO
    IrqSource --> IPlatformLevelInterruptController
    JedecParameter --> JedecParameterPacket
    K6xF_Ethernet --> IBusController
    K6xF_MCG --> ByteRegisterCollection
    K6xF_RNG --> PseudorandomNumberGenerator
    K6xF_UART --> ByteRegisterCollection
    KVMCPU --> HookDescriptor
    KVMCPU --> MinimalRangesCollection
    KVMCPU --> NativeBinder
    LAPIC --> APICMessageHelper
    LAPIC --> IMachine
    LAPIC --> LimitTimer
    LBABackend --> SerializableStreamView
    LC709205F --> IMachine
    LEDTester --> ILed
    LEDTester --> IMachine
    LINBase --> LINDecoder
    LIS2DW12 --> IMachine
    LIS2DW12 --> IManagedThread
    LIS2DW12 --> LIS2DW12_FIFO
    LIS2DW12_FIFO --> LIS2DW12
    LIS2DW12_FIFO --> Vector3DSample
    LLVMAssembler --> ICPUSupportingLLVMDisas
    LLVMDisassembler --> ICPUSupportingLLVMDisas
    LPC_CTimer --> LimitTimer
    LPITTimer --> S32K_LPIT
    LPS25HB --> IManagedThread
    LSM303DLHC_Accelerometer --> GPIO
    LSM6DSO_FIFO --> IMachine
    LSM6DSO_FIFO --> LSM6DSO_IMU
    LSM6DSO_FIFO --> LSM6DSO_Vector3DSample
    LSM6DSO_IMU --> IManagedThread
    LSM6DSO_IMU --> LSM6DSO_FIFO
    Layer --> STM32LTDC
    LimitTimer --> IClockSource
    LimitTimer --> IPeripheral
    LiteSDCard --> IBusController
    LiteSDCard_CSR32 --> IBusController
    LiteX_CPUTimer --> ComparingTimer
    LiteX_Ethernet --> BitBangHelper
    LiteX_Ethernet --> Slot
    LiteX_Ethernet_CSR32 --> BitBangHelper
    LiteX_Ethernet_CSR32 --> Slot
    LiteX_Framebuffer --> IBusController
    LiteX_Framebuffer --> IBusPeripheral
    LiteX_Framebuffer_CSR32 --> IBusController
    LiteX_Framebuffer_CSR32 --> IBusPeripheral
    LiteX_I2C --> BitPatternDetector
    LiteX_I2C --> II2CPeripheral
    LiteX_I2C_Zephyr --> BitPatternDetector
    LiteX_I2C_Zephyr --> II2CPeripheral
    LiteX_I2S_Master --> PCMEncoder
    LiteX_I2S_Slave --> IManagedThread
    LiteX_I2S_Slave --> PCMDecoder
    LiteX_SPI_Flash --> BitBangHelper
    LiteX_Timer --> LimitTimer
    LiteX_Timer64 --> LimitTimer
    LiteX_Timer_CSR32 --> LimitTimer
    Lock --> SEMA4
    LockRegister --> STM32_FlashController
    LogSourcesMap --> WeakWrapper
    LoggerBackend --> LogLevel
    LoggingUartAnalyzer --> IMachine
    LoggingUartAnalyzer --> IUART
    MAX30208 --> IMachine
    MAX32650_PWRSEQ --> MAX32650_RTC
    MAX32650_RTC --> LimitTimer
    MAX32650_TPU --> CRCEngine
    MAX32650_Timer --> IMachine
    MAX32650_UART --> MAX32650_GCR
    MAX32650_WDT --> LimitTimer
    MAX3421E --> IManagedThread
    MAX86171 --> AFESampleFIFO
    MAX86171 --> AFESampleFrame
    MAX86171 --> IMachine
    MAX86171 --> IManagedThread
    MB85RC1MTI2CRelay --> MB85RC1MT
    MC3635 --> IMachine
    MC3635 --> IManagedThread
    MCAN --> IMachine
    MCAN --> IMultibyteWritePeripheral
    MMCController --> IMachine
    MMUWindow --> IEmulationElement
    MPFS_CAN --> RxMessageBuffer
    MPFS_CAN --> TxMessageBuffer
    MPFS_GPIO --> GPIOInterruptManager
    MPFS_I2C --> II2CPeripheral
    MPFS_PCIe --> AddressTranslationTable
    MPFS_PDMA --> DmaEngine
    MPFS_PDMA --> IMachine
    MPFS_RTC --> LimitTimer
    MPFS_SDController --> IBusController
    MPFS_SDController --> IPhysicalLayer
    MPFS_SPI --> DoubleWordRegister
    MPFS_Sysreg --> IBusController
    MPFS_SystemServices --> IBusController
    MPFS_SystemServices --> IMultibyteWritePeripheral
    MPFS_SystemServices --> IQuadWordPeripheral
    MPFS_Timer --> LimitTimer
    MPFS_USB --> ByteRegisterCollection
    MPFS_USB --> WordRegisterCollection
    MPFS_Watchdog --> LimitTimer
    MPFS_eNVM --> LimitTimer
    MPFS_eNVM --> MappedMemory
    MSCM --> GPIO
    MSCM --> IBusController
    MSP430F2XXX_Watchdog --> LimitTimer
    MSP430X --> LLVMAssembler
    MSP430X --> LLVMDisassembler
    MSP430_Timer --> LimitTimer
    MXIC_MX66UM1G45G --> ByteRegister
    MXIC_MX66UM1G45G --> MappedMemory
    MXIC_MX66UM1G45G --> WordRegister
    Machine --> AtomicState
    Machine --> BaseClockSource
    Machine --> PausedState
    Machine --> Player
    Machine --> Recorder
    Machine --> TimeSourceBase
    ManagedThreadWrappingClockEntry --> IMachine
    MappedMemory --> IMachine
    MappedMemory --> IMappedSegment
    MappedMemory --> SharedSegment
    MappedSegment --> MappedMemory
    MappedSegmentWrapper --> ICPUWithMappedMemory
    MappedSegmentWrapper --> IMappedSegment
    MassStorage --> CommandDescriptorBlock
    MassStorage --> CommandStatusWrapper
    MassStorage --> ConfigurationUSBDescriptor
    MassStorage --> DeviceQualifierUSBDescriptor
    MassStorage --> EndpointUSBDescriptor
    MassStorage --> InterfaceUSBDescriptor
    MassStorage --> LBABackend
    MassStorage --> StandardInquiryData
    MassStorage --> StandardUSBDescriptor
    MassStorage --> StringUSBDescriptor
    MatchTimerUnit --> LimitTimer
    MatchTimerUnit --> TimerUnit
    MemoryRegionController --> MemoryRegionDescriptor
    MessageAuthenticationServiceProvider --> IBusController
    MessageAuthenticationServiceProvider --> InternalMemoryManager
    MessageBuffer --> MPFS_CAN
    MiV_CoreGPIO --> GPIOInterruptManager
    MiV_CoreTimer --> IMachine
    MiV_CoreUART --> ByteRegisterCollection
    MockBytePeripheralWithoutTranslations --> ByteRegisterCollection
    MockQuadWordPeripheralWithoutTranslations --> QuadWordRegisterCollection
    MockWordPeripheralWithoutTranslations --> WordRegisterCollection
    Monitor --> EmulationManager
    Monitor --> IMachine
    Monitor --> MonitorPath
    Monitor --> MonitorPythonEngine
    Monitor --> SimpleCache
    Monitor --> Tokenizer
    MonitorCommand --> OpenOcdOverlay
    MonitorPathCommand --> MonitorPath
    MonitorPythonEngine --> Monitor
    MonitorPythonEngine --> StreamToEventConverter
    MonitoredAction --> ProgressMonitor
    MultiTree --> MultiTreeNode
    MultiTreeNode --> MultiTree
    Murax_Timer --> LimitTimer
    MusteinGenericGPU --> IMachine
    MusteinGenericGPU --> MappedMemory
    NANDFlash --> MappedMemory
    NPCX_Flash --> MappedMemory
    NPCX_ITIM --> LimitTimer
    NPCX_MDMA --> DMAChannelContext
    NPCX_MTC --> LimitTimer
    NPCX_SMBus --> II2CPeripheral
    NPCX_SPIP --> WordRegisterCollection
    NPCX_TWD --> IMachine
    NPCX_TWD --> LimitTimer
    NPCX_TWD --> Watchdog
    NRF52840_GPIOTasksEvents --> NRF52840_GPIO
    NRF52840_I2C --> II2CPeripheral
    NRF52840_I2S --> IManagedThread
    NRF52840_I2S --> PCMDecoder
    NRF52840_I2S --> PCMEncoder
    NRF52840_PDM --> IManagedThread
    NRF52840_PDM --> PCMDecoder
    NRF52840_RNG --> PseudorandomNumberGenerator
    NRF52840_RTC --> ComparingTimer
    NRF52840_RTC --> LimitTimer
    NRF52840_SPI --> IBusController
    NRF52840_SPI --> IMachine
    NRF52840_Timer --> ComparingTimer
    NRF52840_UART --> IBusController
    NRF52840_Watchdog --> IMachine
    NRF54H20_GRTC --> ComparingTimer
    NRF54H20_GRTC --> LimitTimer
    NRF54H20_UARTE --> IBusController
    NRF_Bellboard --> IMachine
    NRF_USBD --> IMachine
    NRF_USBD --> USBEndpoint
    NVIC --> CortexM
    NVIC --> ExceptionSimpleArray
    NVIC --> IMachine
    NVIC --> SecurityBanked
    NXPGPIOPort --> DoubleWordRegister
    NXPGPIOPort --> GPIOInterruptManager
    NXP_FLEXCOMM --> IMachine
    NXP_FLEXCOMM --> NXP_LPUART
    NXP_FLEXCOMM --> S32K3XX_LowPowerInterIntegratedCircuit
    NXP_IMX8MP_SystemResetController --> BaseCPU
    NXP_IMX_GPIO --> GPIOLine
    NXP_IMX_I2C --> II2CPeripheral
    NXP_IMX_Watchdog --> LimitTimer
    NXP_LPUART --> IManagedThread
    NXP_OsTimer --> ComparingTimer
    NXP_XRDC --> IPeripheral
    NXP_XRDC --> MasterDomainDescriptor
    NXP_XRDC --> MemoryRegionController
    NXP_XRDC --> PeripheralAccessControlDescriptor
    NXP_XRDC --> PeripheralAccessController
    NXP_eDMA_Channels --> NXP_XRDC
    NXP_eDMA_Channels --> NXP_eDMA
    NXP_uSDHC --> IBusController
    NetworkBackend --> SocketServerProvider
    NetworkInterfaceTester --> IPeripheral
    NetworkWithPHY --> IMachine
    NotNode --> AstNode
    NullRegistrationPointContainerHelper --> IMachine
    NullRegistrationPointContainerHelper --> IPeripheral
    NullRegistrationPointPeripheralContainer --> IMachine
    NullRegistrationPointPeripheralContainer --> NullRegistrationPointContainerHelper
    OV2640 --> ByteRegisterCollection
    OV2640 --> IPeripheral
    OldSymbolProvider --> Symbol
    OldSymbolProvider --> SymbolProvider
    OpenCoresI2C --> ByteRegisterCollection
    OpenCoresI2C --> II2CPeripheral
    OpenOcdOverlay --> CommandsManager
    OpenTitan_AES --> ByteArrayWithAccessTracking
    OpenTitan_AES --> PseudorandomNumberGenerator
    OpenTitan_AonTimer --> ComparingTimer
    OpenTitan_AonTimer --> OpenTitan_PowerManager
    OpenTitan_AonTimer --> OpenTitan_ResetManager
    OpenTitan_BigNumberAccelerator --> IOpenTitan_BigNumberAcceleratorCore
    OpenTitan_BigNumberAccelerator --> OpenTitan_ScrambledMemory
    OpenTitan_BigNumberAcceleratorCore --> OpenTitan_BigNumberAccelerator
    OpenTitan_BigNumberAcceleratorCore --> OpenTitan_ScrambledMemory
    OpenTitan_BigNumberAcceleratorCore --> PseudorandomNumberGenerator
    OpenTitan_BigNumberAcceleratorCore --> WideRegister
    OpenTitan_CSRNG --> FakeEntropy
    OpenTitan_CSRNG --> OpenTitan_EntropySource
    OpenTitan_ClockManager --> OpenTitan_BigNumberAccelerator
    OpenTitan_EntropyDistributionNetwork --> OpenTitan_CSRNG
    OpenTitan_EntropySource --> PseudorandomNumberGenerator
    OpenTitan_EntropySource --> Sha3Conditioner
    OpenTitan_FlashController --> MappedMemory
    OpenTitan_HMAC --> Packer
    OpenTitan_I2C --> II2CPeripheral
    OpenTitan_KeyManager --> OpenTitan_ROMController
    OpenTitan_LifeCycleController --> OpenTitan_OneTimeProgrammableMemoryController
    OpenTitan_LifeCycleController --> OpenTitan_ResetManager
    OpenTitan_OneTimeProgrammableMemoryController --> ArrayMemory
    OpenTitan_PowerManager --> OpenTitan_ResetManager
    OpenTitan_ROMController --> MappedMemory
    OpenTitan_ResetManager --> IPeripheral
    OpenTitan_ScrambledMemory --> IMachine
    OpenTitan_ScrambledMemory --> MappedMemory
    OpenTitan_SpiDevice --> ArrayMemory
    OpenTitan_SpiDevice --> SRAMCircularFifoRange
    OpenTitan_SpiHost --> ISPIPeripheral
    OpenTitan_SystemResetControl --> DurationTimer
    OpenTitan_SystemResetControl --> OpenTitan_ResetManager
    OpenTitan_Timer --> ComparingTimer
    OrNode --> AstNode
    PAC1934 --> ByteRegisterCollection
    PCIHost_Bridge --> IPCIePeripheral
    PCIeBasePeripheral --> BaseAddressRegister
    PCIeBasePeripheral --> IPCIeRouter
    PCMDecoder --> IPeripheral
    PL031 --> IMachine
    PL050 --> PrimeCellIDHelper
    PL110 --> IBusController
    PROTIMER_CaptureCompareChannel --> EFR32xG24_Radio
    PROTIMER_TimeoutCounter --> EFR32xG24_Radio
    PSCIPythonEngine --> ICPUWithPSCI
    PULP_EventController --> PULP_InterruptController
    PULP_I2S --> IManagedThread
    PULP_I2S --> PCMDecoder
    PULP_I2S --> PCMEncoder
    PULP_InterruptController --> PULP_EventController
    PULP_Timer --> ComparingTimer
    PULP_uDMA_Camera --> IBusController
    PULP_uDMA_I2C --> IBusController
    PULP_uDMA_SDIO --> IBusController
    PULP_uDMA_SPI --> IBusController
    PULP_uDMA_UART --> IBusController
    Packer --> IEmulationElement
    PacketBuilder --> PacketData
    PacketFifoBase --> EOSS3_PacketFIFO
    PacketFifoSwitchable --> CircularBuffer
    PacketInfo --> IRadio
    PacketInterceptionPythonEngine --> IMachine
    PacketInterceptionPythonEngine --> IRadio
    PausedState --> Emulation
    PausedState --> IHasOwnLife
    PausedState --> Machine
    PerfettoProfiler --> PerfettoTraceWriter
    PerfettoTraceWriter --> Trace
    PeriodicInterruptTimer --> IMachine
    PeripheralAccessController --> PeripheralAccessControlDescriptor
    PeripheralAccessMethods --> IBusPeripheral
    PeripheralAccessProfiler --> PerfettoTraceWriter
    PeripheralCollection --> SystemBus
    PeripheralNode --> PeripheralTreeEntry
    PeripheralPythonEngine --> PythonPeripheral
    PeripheralPythonEngine --> PythonRequest
    PeripheralRegister --> IPeripheral
    PeripheralsGroupsManager --> IMachine
    PicoRV32 --> LimitTimer
    PicoRV_SPI --> BitBangHelper
    PlatformLevelInterruptControllerBase --> IrqContext
    PlatformLevelInterruptControllerBase --> IrqSource
    Player --> IMachine
    PluginManager --> TypeDefinitionComparer
    PocoJsonSerializerStrategy --> CacheResolver
    PointerHandler --> IPointerInput
    Port --> LPC43xx_GPIO
    Port --> RenesasDA14_GPIO
    PortStatusAndControlRegister --> IUSBPeripheral
    Potato_UART --> QuadWordRegisterCollection
    PowerManagementModule --> ZynqMP_PlatformManagementUnit
    PrimeCellIDHelper --> IPeripheral
    PrivateComparator --> ComparingTimer
    Profiler --> IMachine
    ProfilerStack --> TranslationCPU
    ProfilerStackFrame --> Symbol
    ProgressWidgetMonitor --> ProgressWidget
    PseudorandomBitGenerator --> InternalMemoryManager
    PulseGenerator --> LimitTimer
    Puya_P25Q --> ByteRegisterCollection
    Puya_P25Q --> MappedMemory
    PythonPeripheral --> PeripheralPythonEngine
    Quark_PWM --> LimitTimer
    Quark_SystemControlSubsystem --> LimitTimer
    Quark_SystemControlSubsystem --> Quark_GPIOController
    QuectelModem --> IGPIO
    QuectelModem --> LimitTimer
    QuectelModem --> SocketService
    QueueHead --> IBusController
    QueueHeadOverlay --> IBusController
    QueueTransferDescriptor --> IBusController
    RESDStream --> DataBlock
    RESDStream --> LowLevelRESDParser
    RSAServiceProvider --> InternalMemoryManager
    RTCTimer --> DateTimeWithCustomWeekday
    RTCTimer --> IBusController
    RTCTimer --> IPeripheral
    RTCTimer --> LimitTimer
    RV8803_RTC --> LimitTimer
    RV8803_RTC --> RTCTimer
    ReadLoggingWrapper --> IMachine
    ReceiveDescriptor --> IBusController
    Recorder --> IMachine
    Redirector --> IBusController
    RegisterCollectionHookPythonEngine --> IProvidesRegisterCollection
    RegisterField --> PeripheralRegister
    RegisteredCPU --> Arm
    RegisteredCPU --> ArmSignalsUnit
    RegisteredCPU --> IMachine
    RegsValues --> ConfigRegister
    RenesasDA14_ClockGenerationController --> IMachine
    RenesasDA14_ClockGenerationController --> MappedMemory
    RenesasDA14_ClockGenerationController --> RenesasDA14_XTAL32MRegisters
    RenesasDA14_GPADC --> LimitTimer
    RenesasDA14_GPT --> GPIOConnection
    RenesasDA14_GPT --> LimitTimer
    RenesasDA14_GeneralPurposeRegisters --> RenesasDA_Watchdog
    RenesasDA14_XTAL32MRegisters --> IMachine
    RenesasDA_DMABase --> IMachine
    RenesasDA_I2C --> ByteRegister
    RenesasDA_I2C --> IGPIOReceiver
    RenesasDA_SPI --> ISPIPeripheral
    RenesasDA_Watchdog --> LimitTimer
    RenesasDA_Watchdog --> NVIC
    RenesasRA6M5_SCI --> II2CPeripheral
    RenesasRA6M5_SCI --> IMachine
    RenesasRA6M5_SCI --> IUART
    RenesasRA8M1_SCI --> II2CPeripheral
    RenesasRA8M1_SCI --> IMachine
    RenesasRA_AGT --> CompareChannel
    RenesasRA_AGT --> IMachine
    RenesasRA_AGT --> LimitTimer
    RenesasRA_GPIO --> RenesasRA_GPIOMisc
    RenesasRA_GPT --> GPTChannel
    RenesasRA_GPT --> IMachine
    RenesasRA_ICU --> IGPIOReceiver
    RenesasRA_IIC --> ByteRegister
    RenesasRA_IIC --> Condition
    RenesasRA_IIC --> II2CPeripheral
    RenesasRZG_CPG_SYSC --> CortexM
    RenesasRZG_CPG_SYSC --> ICPU
    RenesasRZG_CPG_SYSC --> RenesasRZG_Watchdog
    RenesasRZG_DMAC --> IBusController
    RenesasRZG_GPIO --> ByteRegisterCollection
    RenesasRZG_GPIO --> GPIO
    RenesasRZG_GPIO --> WordRegisterCollection
    RenesasRZG_GPT --> GPTChannel
    RenesasRZG_GPT --> IMachine
    RenesasRZG_GTM --> LimitTimer
    RenesasRZG_IIC --> Condition
    RenesasRZG_IIC --> DoubleWordRegister
    RenesasRZG_IIC --> II2CPeripheral
    RenesasRZG_IRQController --> GPIO
    RenesasRZG_MHU --> GPIO
    RenesasRZG_SCIFA --> WriteAllowedAfterReadingOneFlag
    RenesasRZG_SPI --> ByteRegisterCollection
    RenesasRZG_SPI --> WordRegisterCollection
    RenesasRZG_SYC --> LimitTimer
    RenesasRZG_Watchdog --> IMachine
    RenesasRZG_Watchdog --> LimitTimer
    Renesas_GPIO --> ByteRegisterCollection
    Renesas_GPIO --> WordRegisterCollection
    ResetPin --> IMachine
    ResourceBlock --> IResourceBlockOwner
    ResourceBlocksManager --> IEmulationElement
    ReverseExecutionCommand --> PacketData
    RiscVCsrPythonEngine --> CsrRequest
    RiscVCsrPythonEngine --> ICPU
    RiscVDisassemblerWrapper --> IFlaglessDisassembler
    RiscVInstructionPythonEngine --> BaseRiscV
    RiscVMachineTimer --> ComparingTimer
    RiscVMachineTimer --> IMachine
    RiscVStackAccessPythonEngine --> BaseRiscV
    RunningInterrupts --> CPUEntry
    S32K3XX_FlexCAN --> ArrayMemory
    S32K3XX_FlexIO_SENT --> IBusController
    S32K3XX_FlexIO_SENT --> LimitTimer
    S32K3XX_FlexIO_SENT --> S32K3XX_FlexIO
    S32K3XX_FlexIO_UART --> S32K3XX_FlexIO
    S32K3XX_FlexIO_UART --> UARTReceiver
    S32K3XX_FlexIO_UART --> UARTTransmitter
    S32K3XX_LowPowerInterIntegratedCircuit --> II2CPeripheral
    S32K3XX_MiscellaneousSystemControlModule --> WordRegisterCollection
    S32K3XX_PLLDIG --> S32K3XX_MC_CGM
    S32K3XX_RealTimeClock --> InternalClock
    S32K3XX_SoftwareWatchdogTimer --> LimitTimer
    S32K3XX_SystemIntegrationUnitLite2 --> ByteRegisterCollection
    S32K3XX_SystemTimerModule --> IMachine
    S32K3XX_SystemTimerModule --> LimitTimer
    S32K3XX_eMIOS --> IBusController
    S32K3XX_eMIOS --> UnifiedChannel
    S32KXX_ModeEntryModule --> ICPU
    S32K_LPIT --> LPITTimer
    S32K_LPTMR --> ComparingTimer
    SAM4S_ADC --> LimitTimer
    SAM4S_CRCCU --> CRCEngine
    SAM4S_EEFC --> IMemory
    SAM4S_PIO --> GPIOInterruptManager
    SAM4S_RSTC --> CortexM
    SAM4S_TWI --> II2CPeripheral
    SAM4S_TWI --> SAM_PDC
    SAM4S_WDT --> IMachine
    SAM4S_WDT --> SAM4S_RSTC
    SAMD21_GPIO --> DoubleWordRegister
    SAMD21_I2C --> ByteRegisterCollection
    SAMD21_I2C --> II2CPeripheral
    SAMD21_I2C --> WordRegisterCollection
    SAMD21_Timer --> LimitTimer
    SAM_PDC --> DmaEngine
    SAM_PDC --> IMachine
    SAM_PDC --> ISamPdcPeripheral
    SAM_SPI --> SAM_PDC
    SAM_TRNG --> PseudorandomNumberGenerator
    SAM_USART --> SAM_PDC
    SDCard --> CRCEngine
    SDCard --> SpiContext
    SDCard --> Stream
    SDCard --> VariableLengthValue
    SEMA4 --> IBusController
    SEMA4 --> Lock
    SEMA42 --> ByteRegisterCollection
    SEMA42 --> IBusController
    SEMA42 --> NXP_XRDC
    SEMA42 --> WordRegisterCollection
    SENTPeripheralBase --> Transmitter
    SFDPData --> FourByteCommandsSupportParameter
    SHT45 --> CRCEngine
    SMC91X --> MemoryRegion
    SMSC9500 --> ConfigurationUSBDescriptor
    SMSC9500 --> DeviceQualifierUSBDescriptor
    SMSC9500 --> EndpointUSBDescriptor
    SMSC9500 --> InterfaceUSBDescriptor
    SMSC9500 --> StandardUSBDescriptor
    SMSC9500 --> StringUSBDescriptor
    SRAMCircularFifoRange --> ArrayMemory
    STM32DMA --> DmaEngine
    STM32DMA --> Stream
    STM32DMA2D --> DoubleWordRegister
    STM32DMA2D --> IBusController
    STM32DMA2D --> IPixelBlender
    STM32DMA2D --> IPixelConverter
    STM32F1AFIO --> GPIORedirector
    STM32F1AFIO --> STM32F1GPIOPort
    STM32F1GPIOPort --> GPIOAlternateFunction
    STM32F1_I2C --> II2CPeripheral
    STM32F4_EXTI --> STM32_EXTICore
    STM32F4_FlashController --> LockRegister
    STM32F4_FlashController --> MappedMemory
    STM32F4_RTC --> AlarmConfig
    STM32F4_RTC --> LimitTimer
    STM32F4_RTC --> TimerConfig
    STM32F7_I2C --> II2CPeripheral
    STM32G0DMA --> DmaEngine
    STM32G0DMA --> IMachine
    STM32H7_CRYPTO --> AlgorithmState
    STM32H7_EXTI --> STM32_EXTICore
    STM32H7_FlashController --> LockRegister
    STM32H7_HardwareSemaphore --> Semaphore
    STM32H7_SystemWindowWatchdog --> LimitTimer
    STM32L0_FlashController --> DoubleWordRegister
    STM32L0_FlashController --> LockRegister
    STM32L0_FlashController --> MappedMemory
    STM32L0_LpTimer --> LimitTimer
    STM32L0_RCC --> IHasDivisibleFrequency
    STM32L0_RCC --> IPeripheral
    STM32L0_RCC --> ITimer
    STM32LDMA --> DmaEngine
    STM32LTDC --> IBusController
    STM32LTDC --> IPixelBlender
    STM32LTDC --> Layer
    STM32SDMMC --> DoubleWordRegister
    STM32SPI --> CircularBuffer
    STM32WBA55_GPDMA --> DmaEngine
    STM32WBA55_GPDMA --> IMachine
    STM32WBA_EXTI --> STM32_EXTICore
    STM32WBA_FlashController --> LockRegister
    STM32WBA_FlashController --> MappedMemory
    STM32WBA_RCC --> IHasFrequency
    STM32_ADC --> ADCChannel
    STM32_ADC --> LimitTimer
    STM32_ADC_Common --> IDMA
    STM32_ADC_Common --> IMachine
    STM32_ADC_Common --> IManagedThread
    STM32_CRC --> CRCEngine
    STM32_EXTICore --> IPeripheral
    STM32_FDCAN --> ArrayMemory
    STM32_FDCAN --> IManagedThread
    STM32_FDCAN --> LimitTimer
    STM32_GPIOPort --> GPIOAlternateFunction
    STM32_IndependentWatchdog --> LimitTimer
    STM32_RNG --> PseudorandomNumberGenerator
    STM32_Timer --> CaptureCompareChannel
    STM32_Timer --> IBusController
    STM32_Timer --> IMachine
    STMCAN --> FilterBank
    STMCAN --> STMCAN
    STP08ShiftRegister --> IMachine
    SVDParser --> IBusController
    SamplesData --> SafeBinaryReader
    SamsungK9NANDFlash --> Stream
    SemihostingDescriptor --> SemihostingHandler
    SemihostingDescriptor --> Stream
    SemihostingHandler --> Arm
    SemihostingHandler --> IMachine
    SemihostingHandler --> PriorityQueue
    SemihostingHandler --> SemihostingUart
    SerializableStreamView --> Stream
    ServerSocketTerminal --> SocketServerProvider
    SetAndRevertAfterCommand --> DeviceHandlingHelpers
    SetAndRevertAfterCommand --> ExternalsHandler
    SetAndRevertAfterCommand --> SimpleCache
    SevenSegmentsDisplay --> Digit
    Signal --> IPeripheral
    SignalsDictionary --> Signal
    Silabs_SecureElement --> IDoubleWordPeripheral
    Silabs_SecureElement --> Machine
    SimpleContainer --> IMachine
    SimpleContainerHelper --> IMachine
    SimpleContainerHelper --> IPeripheral
    SimpleDMA --> IBusController
    SimpleInstructionDecoder --> SimpleInstructionDecoder
    SimpleMemoryManager --> TranslationCPU
    SlaveTimeSource --> TimeHandle
    SlipRadio --> PtyUnixStream
    SnapshotTracker --> SnapshotComparer
    SocketIOSource --> SocketServerProvider
    SocketService --> IEmulatedNetworkService
    SocketUartAnalyzer --> SimpleActiveIOSource
    SocketUartAnalyzer --> SocketServerProvider
    SortedIntervals --> Symbol
    SortedIntervals --> SymbolLookup
    Sparc --> GaislerMIC
    SpiHost --> ISPIPeripheral
    StartCommand --> IncludeFileCommand
    Stream --> STM32DMA
    SunxiHighSpeedTimer --> DoubleWordRegister
    SunxiHighSpeedTimer --> SunxiHighSpeedTimerUnit
    SunxiHighSpeedTimerUnit --> DoubleWordRegister
    SunxiMMC --> DmaEngine
    SunxiMMC --> DoubleWordRegister
    SunxiTimer --> DoubleWordRegister
    SunxiTimer --> SunxiTimerUnit
    SunxiTimerUnit --> DoubleWordRegister
    SunxiTimerUnit --> SunxiTimer
    SymbolLookup --> SortedIntervals
    SymbolProvider --> Symbol
    SyncPointHookPythonEngine --> Emulation
    SynopsysDWCEthernetQualityOfService --> DMAChannel
    SynopsysDWCEthernetQualityOfService --> LimitTimer
    SynopsysEthernetMAC --> IBusController
    SysTick --> LimitTimer
    SysTick --> NVIC
    SysbusReaderWriterBase --> IBusController
    SysbusTester --> IMachine
    SystemBus --> SymbolLookup
    SystemBus --> ThreadLocalContext
    SystemRegister --> ArmSystemRegisterEncoding
    TargetBar --> IPCIePeripheral
    TegraDisplay --> IBusController
    TegraDma --> DmaEngine
    TegraDmaHost1X --> DmaEngine
    TegraDmaHost1X --> IBusController
    TegraTimer --> IClockSource
    TerminalTester --> IMachine
    TerminalTester --> SafeStringBuilder
    TerminalTester --> TerminalTesterResult
    TexasInstrumentsTimer --> DoubleWordRegister
    TexasInstrumentsTimer --> LimitTimer
    TimeSourceBase --> HandlesCollection
    TimeSourceBase --> PrioritySynchronizer
    TimeSourceBase --> TimeVariantValue
    TimeoutEvent --> TimeSourceBase
    TimerConfig --> STM32F4_RTC
    TimerUnit --> ComparingTimer
    TimerUnit --> Gaisler_GPTimer
    TimerUnit --> IClockSource
    TimerUnit --> IGPIO
    TimerUnit --> IPeripheral
    TimerUnit --> LimitTimer
    TraceBinaryWriter --> LRUCache
    TraceWriter --> Stream
    TraceWriterBuilder --> TranslationCPU
    Transceiver --> GPIO
    Transceiver --> IMXRT700_SAI
    Transceiver --> IMachine
    Transceiver --> IManagedThread
    Transceiver --> PCMDecoder
    Transceiver --> PCMEncoder
    TranslationCPU --> AtomicState
    TranslationCPU --> BaseProfiler
    TranslationCPU --> CpuThreadPauseGuard
    TranslationCPU --> HookDescriptorBase
    TranslationCPU --> LLVMAssembler
    TranslationCPU --> LLVMDisassembler
    TranslationCPU --> MinimalRangesCollection
    TranslationCPU --> NativeBinder
    TranslationCPU --> SimpleMemoryManager
    TransmitBuffer --> LPC_CAN
    TransmitDescriptor --> IBusController
    Transmitter --> IMachine
    Transmitter --> IManagedThread
    UARTBackend --> CircularBuffer
    UARTDirectionBase --> IEmulationElement
    UARTDirectionBase --> Shifter
    UARTRESDFeeder --> IMachine
    UDMA --> DmaEngine
    UDMA --> IBusController
    UFSDevice --> Stream
    UFSHostController --> IBusController
    USBConfiguration --> IUSBDevice
    USBConnector --> IUSBDevice
    USBDeviceCore --> IUSBDevice
    USBEndpoint --> IUSBDevice
    USBEndpoint --> PacketCreator
    USBEthernetControlModelDevice --> EndpointUSBDescriptor
    USBEthernetControlModelDevice --> InterfaceUSBDescriptor
    USBHost --> TimeSourceBase
    USBIPServer --> SocketServerProvider
    USBInterface --> IUSBDevice
    USBKeyboard --> ConfigurationUSBDescriptor
    USBKeyboard --> DeviceQualifierUSBDescriptor
    USBKeyboard --> EndpointUSBDescriptor
    USBKeyboard --> InterfaceUSBDescriptor
    USBKeyboard --> StandardUSBDescriptor
    USBKeyboard --> StringUSBDescriptor
    USBKeyboard --> USBEndpoint
    USBMouse --> ConfigurationUSBDescriptor
    USBMouse --> DeviceQualifierUSBDescriptor
    USBMouse --> EndpointUSBDescriptor
    USBMouse --> InterfaceUSBDescriptor
    USBMouse --> StandardUSBDescriptor
    USBMouse --> StringUSBDescriptor
    USBMouse --> USBEndpoint
    USBPendrive --> Stream
    USBPendrive --> USBEndpoint
    USBTablet --> ConfigurationUSBDescriptor
    USBTablet --> DeviceQualifierUSBDescriptor
    USBTablet --> EndpointUSBDescriptor
    USBTablet --> InterfaceUSBDescriptor
    USBTablet --> StandardUSBDescriptor
    USBTablet --> StringUSBDescriptor
    UartFileBackend --> IUART
    UartPythonEngine --> IMachine
    UartPythonEngine --> IUART
    UartStream --> SemihostingUart
    UnifiedChannel --> IGPIO
    UnifiedChannel --> LimitTimer
    UnifiedChannel --> S32K3XX_eMIOS
    UsbHub --> ConfigurationUSBDescriptor
    UsbHub --> DeviceQualifierUSBDescriptor
    UsbHub --> EndpointUSBDescriptor
    UsbHub --> HubUSBDescriptor
    UsbHub --> IMachine
    UsbHub --> InterfaceUSBDescriptor
    UsbHub --> StandardUSBDescriptor
    UsbHub --> StringUSBDescriptor
    UserStatePythonEngine --> IMachine
    VeeR_EL2 --> InternalTimerBlock
    VeeR_EL2 --> LimitTimer
    VeeR_EL2_PIC --> VeeR_EL2
    VideoAnalyzer --> Button
    VideoAnalyzer --> FrameBufferDisplayWidget
    VideoAnalyzer --> IPeripheral
    VirtIOBlockDevice --> Stream
    VirtIOMMIOConsole --> ConsolePort
    VirtIOMMIOEntropy --> PseudorandomNumberGenerator
    Virtqueue --> VirtIO
    VirtualConsole --> IBusController
    VybridDCU --> IBusController
    VybridDma --> DmaEngine
    VybridDma --> IMachine
    WFIPythonEngine --> ICPUWithHooks
    WFIPythonEngine --> IMachine
    Watchdog --> NPCX_TWD
    WatchpointHookPythonEngine --> IBusController
    WebSocketConnection --> WebSocketConnectionSharedData
    WebSocketIOSource --> WebSocketSingleConnectionServer
    WebSocketNetworkBackend --> WebSocketSingleConnectionServer
    WebSocketServerProvider --> WebSocketConnectionSharedData
    WebSocketUartAnalyzer --> SimpleActiveIOSource
    WebSocketUartAnalyzer --> WebSocketSingleConnectionServer
    WindowIOMMU --> WindowMMUBusController
    WindowMMUBusController --> IEmulationElement
    WirelessMedium --> IMediumFunction
    WrappingQueue --> ARM_SMMUv3
    WrappingQueue --> IBusController
    WriteAllowedAfterReadingOneFlag --> IPeripheral
    WriteLoggingWrapper --> IMachine
    X11EventSource --> FrameBufferDisplayWidget
    X11EventSource --> IOHandler
    XWTEventSource --> IOHandler
    XilinxGPIOPS --> GPIOController
    XilinxQSPI --> RegsValues
    Xilinx_XADC --> DoubleWordRegister
    Xtensa --> ComparingTimer
    Xtensa --> SemihostingUart
    ZynqMP_GQSPI --> IBusController
    ZynqMP_IPI --> IMemory
    ZynqMP_IPI --> ZynqMP_PlatformManagementUnit
    ZynqMP_PlatformManagementUnit --> PowerManagementModule
    ZynqMP_PlatformManagementUnit --> ZynqMP_IPI
    ZynqMP_RTC --> LimitTimer
    %% cycle: AFESampleFIFO <-> MAX86171
    %% cycle: ARM_GenericInterruptController <-> CPUEntry
    %% cycle: ARM_SMMUv3 <-> Domain
    %% cycle: AddressTranslationTable <-> MPFS_PCIe
    %% cycle: AlarmConfig <-> STM32F4_RTC
    %% cycle: AlgorithmState <-> STM32H7_CRYPTO
    %% cycle: AmbiqApollo4_SystemTimer <-> CaptureRegister
    %% cycle: AmbiqApollo4_SystemTimer <-> CompareRegister
    %% cycle: ArchitectureDecoder <-> BaseRiscV
    %% cycle: Arm <-> ArmPerformanceMonitoringUnit
    %% cycle: Arm <-> SemihostingHandler
    %% cycle: ArmSignalsUnit <-> ArmSnoopControlUnit
    %% cycle: BUFC_Buffer <-> EFR32xG24_Radio
    %% cycle: BaseProfiler <-> TranslationCPU
    %% cycle: BaseRiscV <-> CoreLocalInterruptController
    %% cycle: BaseRiscV <-> ExternalPMPBase
    %% cycle: Cadence_USB <-> DMACore
    %% cycle: CaptureCompareChannel <-> STM32_Timer
    %% cycle: CommandsEngine <-> IMXRT_FlexSPI
    %% cycle: CommunicationHandler <-> GdbStub
    %% cycle: Condition <-> RenesasRA_IIC
    %% cycle: Condition <-> RenesasRZG_IIC
    %% cycle: Connection <-> DA16200
    %% cycle: ConsolePort <-> ConsolePort
    %% cycle: ConsolePort <-> VirtIOMMIOConsole
    %% cycle: CortexM <-> NVIC
    %% cycle: CpuThreadPauseGuard <-> TranslationCPU
    %% cycle: DA16200 <-> DataModeState
    %% cycle: DMAChannel <-> SynopsysDWCEthernetQualityOfService
    %% cycle: DMAChannelContext <-> NPCX_MDMA
    %% cycle: EFR32xG24_Radio <-> PROTIMER_CaptureCompareChannel
    %% cycle: EFR32xG24_Radio <-> PROTIMER_TimeoutCounter
    %% cycle: EOSS3_PacketFIFO <-> PacketFifoBase
    %% cycle: FrameBufferDisplayWidget <-> IOHandler
    %% cycle: GPIOAlternateFunction <-> STM32F1GPIOPort
    %% cycle: GPIOAlternateFunction <-> STM32_GPIOPort
    %% cycle: GPIOConnection <-> RenesasDA14_GPT
    %% cycle: GPIOController <-> XilinxGPIOPS
    %% cycle: GPTChannel <-> RenesasRA_GPT
    %% cycle: GPTChannel <-> RenesasRZG_GPT
    %% cycle: Gaisler_GPTimer <-> TimerUnit
    %% cycle: IMXRT700_SAI <-> Transceiver
    %% cycle: LIS2DW12 <-> LIS2DW12_FIFO
    %% cycle: LPITTimer <-> S32K_LPIT
    %% cycle: LSM6DSO_FIFO <-> LSM6DSO_IMU
    %% cycle: Layer <-> STM32LTDC
    %% cycle: Lock <-> SEMA4
    %% cycle: Machine <-> PausedState
    %% cycle: Monitor <-> MonitorPythonEngine
    %% cycle: MultiTree <-> MultiTreeNode
    %% cycle: NPCX_TWD <-> Watchdog
    %% cycle: PULP_EventController <-> PULP_InterruptController
    %% cycle: PeripheralPythonEngine <-> PythonPeripheral
    %% cycle: PowerManagementModule <-> ZynqMP_PlatformManagementUnit
    %% cycle: S32K3XX_eMIOS <-> UnifiedChannel
    %% cycle: STM32DMA <-> Stream
    %% cycle: STM32F4_RTC <-> TimerConfig
    %% cycle: STMCAN <-> STMCAN
    %% cycle: SimpleInstructionDecoder <-> SimpleInstructionDecoder
    %% cycle: SimpleMemoryManager <-> TranslationCPU
    %% cycle: SortedIntervals <-> SymbolLookup
    %% cycle: SunxiTimer <-> SunxiTimerUnit
    %% cycle: ZynqMP_IPI <-> ZynqMP_PlatformManagementUnit
