#!/usr/bin/env python3
"""Compile EVERYTHING the converter emits, and classify what rustc says.

The gap census answers "what does the converter know it cannot do". This
answers a different and harsher question: **of the code it was confident
enough to emit, how much actually compiles?**

Those are not the same, and until now we only had the first. Two peripherals
are wired into the workspace and compiled on every commit; the other twenty-odd
types the converter can emit have never been near a compiler. c2rust emits
output >99.99% of the time and only 72.64% of it runs -- "we emitted it" is
worth very little on its own.

Method is the one the literature keeps arriving at independently:

  * Laertes uses the Rust compiler as an oracle, and argues you must, because
    "the analysis must be tuned to be no more precise than the Rust compiler".
  * Bun grouped ~16,000 `cargo check` errors into a work queue.
  * Corrode's `corrode-cc` fell back to the real compiler on failure and
    hash-deduped each error message into a file, giving a free coverage metric.

An error CODE is a better work item than a gap, because rustc has already
classified the problem and pointed at the span.

Nothing is written to the repo: the scratch crate lives under tmp/.

Run:  python3 scripts/compile_check.py
      python3 scripts/compile_check.py --keep     # leave the crate for poking
Log:  ./tmp/logs/compile_check.log
Exit: 0 always -- this is a measurement, not a gate. Making it a gate before
      the numbers are known would just block every commit.
"""

from __future__ import annotations

import argparse
import collections
import contextlib
import io
import json
import logging
import shutil
import sqlite3
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))


def repo_root() -> Path:
    return Path(subprocess.run(["git", "rev-parse", "--show-toplevel"],
                               capture_output=True, text=True,
                               check=True).stdout.strip())


def emit_all(root: Path, db: Path, log: logging.Logger) -> list[tuple[str, int]]:
    """Emit every type with a register-defining method into a scratch crate."""
    from emit import Emitter
    quiet = logging.getLogger("quiet")
    quiet.addHandler(logging.NullHandler())

    con = sqlite3.connect(f"file:{db}?mode=ro", uri=True)
    rows = con.execute("""
        SELECT t.name, MIN(mb.name) FROM type t
        JOIN member mb ON mb.type_id = t.id
        JOIN method m ON m.member_id = mb.id
        WHERE t.kind='class' AND m.has_body=1
          AND (mb.name LIKE '%Register%' OR mb.name LIKE '%DefineReg%')
        GROUP BY t.name ORDER BY t.name""").fetchall()

    crate = root / "tmp" / "compile_check"
    shutil.rmtree(crate, ignore_errors=True)
    (crate / "src").mkdir(parents=True)

    mods: list[tuple[str, int]] = []
    for name, method in rows:
        em = Emitter(sqlite3.connect(f"file:{db}?mode=ro", uri=True), quiet)
        try:
            with contextlib.redirect_stderr(io.StringIO()):
                out = em.emit_file(name, method, "m")
        except Exception as exc:                          # noqa: BLE001
            log.warning("emit crashed on %s: %s", name, exc)
            continue
        mod = "".join(c if c.isalnum() else "_" for c in name).lower()
        (crate / "src" / f"{mod}.rs").write_text(out)
        mods.append((mod, len(out.splitlines())))

    (crate / "src" / "lib.rs").write_text(
        "//! Scratch crate: every module the converter can emit, compiled\n"
        "//! together so rustc can say what is actually wrong. Generated by\n"
        "//! scripts/compile_check.py; not part of the workspace.\n"
        "#![allow(dead_code, unused_variables, unused_mut, unused_imports)]\n\n"
        + "\n".join(f"pub mod {m};" for m, _ in sorted(mods)) + "\n")

    (crate / "Cargo.toml").write_text(
        "[package]\nname = \"compile-check\"\nedition = \"2021\"\n"
        "version = \"0.0.0\"\npublish = false\n\n"
        "[dependencies]\n"
        f"renode-regs = {{ path = \"{'../../src/renode-regs'}\" }}\n"
        f"csharp-rt = {{ path = \"{'../../src/csharp-rt'}\" }}\n"
        "log = \"0.4\"\n\n[workspace]\n")
    return mods


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--db", default="rulesdb/patterns.db")
    ap.add_argument("--keep", action="store_true", help="leave the scratch crate")
    ap.add_argument("--ratchet", action="store_true",
                    help="fail if errors rose above docs/status/compile_baseline.json")
    args = ap.parse_args()

    root = repo_root()
    (root / "tmp" / "logs").mkdir(parents=True, exist_ok=True)
    log = logging.getLogger("compile_check")
    log.setLevel(logging.INFO)
    for h in (logging.FileHandler(root / "tmp" / "logs" / "compile_check.log",
                                  mode="w"), logging.StreamHandler(sys.stdout)):
        h.setFormatter(logging.Formatter("%(message)s"))
        log.addHandler(h)

    mods = emit_all(root, root / args.db, log)
    total_lines = sum(n for _, n in mods)
    log.info("emitted %d module(s), %s lines", len(mods), f"{total_lines:,}")

    crate = root / "tmp" / "compile_check"
    proc = subprocess.run(
        ["cargo", "check", "--message-format=json", "--quiet"],
        cwd=crate, capture_output=True, text=True)

    codes: collections.Counter = collections.Counter()
    per_mod: collections.Counter = collections.Counter()
    examples: dict[str, str] = {}
    total = 0
    for line in proc.stdout.splitlines():
        try:
            msg = json.loads(line)
        except json.JSONDecodeError:
            continue
        if msg.get("reason") != "compiler-message":
            continue
        d = msg.get("message", {})
        if d.get("level") != "error":
            continue
        total += 1
        code = (d.get("code") or {}).get("code") or "no-code"
        codes[code] += 1
        examples.setdefault(code, (d.get("message") or "")[:88])
        for span in d.get("spans", []):
            f = span.get("file_name", "")
            if f.endswith(".rs"):
                per_mod[Path(f).stem] += 1
                break

    log.info("")
    if total == 0:
        log.info("ALL %d MODULES COMPILE. %s lines.", len(mods), f"{total_lines:,}")
        log.info("That is a stronger statement than the gap count -- it says the")
        log.info("code the converter was confident enough to emit is at least")
        log.info("well-formed. It says nothing about whether it is CORRECT.")
    else:
        log.info("%-14s %7s  %s", "rustc code", "count", "example")
        log.info("%s", "-" * 78)
        for code, n in codes.most_common(20):
            log.info("%-14s %7d  %s", code, n, examples.get(code, "")[:56])
        log.info("%s", "-" * 78)
        log.info("%d error(s) across %d module(s)", total, len(per_mod))
        log.info("")
        log.info("worst modules:")
        for m, n in per_mod.most_common(8):
            log.info("    %-34s %4d", m, n)

    clean = len(mods) - len(per_mod)
    log.info("")
    log.info("%d of %d modules compile clean", clean, len(mods))
    log.info("")
    log.info("An error CODE is a better work item than a gap: rustc has already")
    log.info("classified the problem and pointed at the span. A gap is what the")
    log.info("converter KNOWS it cannot do; these are what it got wrong anyway.")

    if not args.keep:
        shutil.rmtree(crate, ignore_errors=True)

    if args.ratchet:
        import json as _json
        bf = root / "docs" / "status" / "compile_baseline.json"
        base = _json.loads(bf.read_text()) if bf.exists() else {"errors": 10**9}
        allowed = int(base.get("errors", 10**9))
        if total > allowed:
            log.error("")
            log.error("RATCHET: %d errors, baseline allows %d.", total, allowed)
            log.error("Something that used to compile no longer does. A rule")
            log.error("that quietly stops being applied looks exactly like a")
            log.error("rule that correctly declines -- this is the check that")
            log.error("tells the two apart.")
            return 1
        if total < allowed:
            log.info("")
            log.info("RATCHET: %d errors, below the baseline of %d -- lower it "
                     "in docs/status/compile_baseline.json.", total, allowed)
    return 0


if __name__ == "__main__":
    sys.exit(main())
