#!/usr/bin/env python3
"""Regenerate docs/issues.md from GitHub.

GitHub is the source of truth for issues. A hand-maintained draft of the same
content is a second source that drifts -- `docs/issues-draft.md` was 1,073
lines duplicating issues that were all already filed, and it had drifted.

This keeps the repo navigable offline and after a context compaction, without
the drift: it is generated, and the header says so.

Run:  python3 scripts/issue_index.py
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

REPO = "awtoau/awto-renode-rs"


def main() -> int:
    root = Path(subprocess.run(["git", "rev-parse", "--show-toplevel"],
                               capture_output=True, text=True,
                               check=True).stdout.strip())
    proc = subprocess.run(
        ["gh", "issue", "list", "--repo", REPO, "--state", "all",
         "--limit", "200", "--json", "number,title,state,labels"],
        capture_output=True, text=True)
    if proc.returncode != 0:
        print("gh failed (offline?); leaving docs/issues.md alone",
              file=sys.stderr)
        return 0

    rows = sorted(json.loads(proc.stdout), key=lambda x: x["number"])
    out = ["# Issues", "",
           "Generated by `scripts/issue_index.py`. GitHub is the source of truth;",
           "this exists so the repo is navigable offline and after a compaction.",
           "Do not hand-edit -- regenerate.", ""]
    for head, sel in (("Open", "OPEN"), ("Closed", None)):
        group = [x for x in rows
                 if (x["state"] == "OPEN") == (sel == "OPEN")]
        if not group:
            continue
        out += [f"## {head} ({len(group)})", ""]
        for x in group:
            labs = ",".join(sorted(l["name"] for l in x["labels"]))
            out.append(
                f"- [#{x['number']}](https://github.com/{REPO}/issues/{x['number']}) "
                f"{x['title']}" + (f"  `{labs}`" if labs else ""))
        out.append("")
    (root / "docs" / "issues.md").write_text("\n".join(out))
    print(f"wrote docs/issues.md: {len(rows)} issue(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
